import { Project } from '../types';

export const projects: Project[] = [
  {
    id: "10-cai-tao-nha-lao-cai-4-3x19",
    index: "01",
    title: "CẢI TẠO NHÀ LÀO CAI 4.3X19",
    tagline: "Dự án • Diện tích: 4.3x19",
    description: "Dự án Cải tạo nhà Lào Cai 4.3x19 mang phong cách hiện đại, được thiết kế với sự tinh tế và tiện nghi tối đa.",
    mainImage: "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG - 3 (1).webp",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách hiện đại.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Lào Cai",
      "Diện tích: 4.3x19",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Lào Cai",
    area: "4.3x19",
    style: "HIEN_DAI",
    gallery: [
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG - 3 (1).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG - 3 (2).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG - 3 (3).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG - 3 (4).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG - 3 (5).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG - 3 (6).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG - 3 (7).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG - 3 (8).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG - 3 (9).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -1 (1).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -1 (10).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -1 (11).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -1 (12).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -1 (13).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -1 (2).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -1 (3).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -1 (4).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -1 (5).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -1 (6).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -1 (7).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -1 (8).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -1 (9).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -2 (1).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -2 (2).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -2 (3).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -2 (4).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -2 (5).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -2 (6).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -2 (7).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -2 (8).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/TANG -2 (9).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/master (8).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/ngu phu (1).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/ngu phu (2).webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/p tho.webp",
      "/asset/anhweb/hiện đại/10. Cải tạo nhà Lào Cai 4.3x19/sanh.webp"
    ]
  },
  {
    id: "11-chung-cu-masteri-72m2",
    index: "02",
    title: "CHUNG CƯ MASTERI 72M2",
    tagline: "Dự án • Diện tích: 72 m²2",
    description: "Dự án Chung cư masteri 72m2 mang phong cách hiện đại, được thiết kế với sự tinh tế và tiện nghi tối đa.",
    mainImage: "/asset/anhweb/hiện đại/11. Chung cư masteri 72m2/1.1.webp",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách hiện đại.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 72 m²2",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "72 m²2",
    style: "HIEN_DAI",
    gallery: [
      "/asset/anhweb/hiện đại/11. Chung cư masteri 72m2/1.1.webp",
      "/asset/anhweb/hiện đại/11. Chung cư masteri 72m2/1.webp",
      "/asset/anhweb/hiện đại/11. Chung cư masteri 72m2/11.webp",
      "/asset/anhweb/hiện đại/11. Chung cư masteri 72m2/13.webp",
      "/asset/anhweb/hiện đại/11. Chung cư masteri 72m2/15.webp",
      "/asset/anhweb/hiện đại/11. Chung cư masteri 72m2/17.webp",
      "/asset/anhweb/hiện đại/11. Chung cư masteri 72m2/19.webp",
      "/asset/anhweb/hiện đại/11. Chung cư masteri 72m2/21.webp",
      "/asset/anhweb/hiện đại/11. Chung cư masteri 72m2/3.webp",
      "/asset/anhweb/hiện đại/11. Chung cư masteri 72m2/5.webp",
      "/asset/anhweb/hiện đại/11. Chung cư masteri 72m2/7.webp",
      "/asset/anhweb/hiện đại/11. Chung cư masteri 72m2/9.webp"
    ]
  },
  {
    id: "12-biet-thu-oceanpark-hai-au-230m2",
    index: "03",
    title: "BIỆT THỰ OCEANPARK - HẢI ÂU 230M2",
    tagline: "Dự án • Diện tích: 230 m²2",
    description: "Dự án Biệt thự Oceanpark - Hải Âu 230m2 mang phong cách hiện đại, được thiết kế với sự tinh tế và tiện nghi tối đa.",
    mainImage: "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/1.webp",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách hiện đại.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 230 m²2",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "230 m²2",
    style: "HIEN_DAI",
    gallery: [
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/1.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/10.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/11.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/12.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/13.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/131.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/14.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/15.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/16.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/17.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/18.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/19.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/2.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/20.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/21.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/22.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/23.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/24.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/25.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/26.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/27.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/28.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/29.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/3.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/30.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/31.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/4.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/5.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/6.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/7.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/8.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/9.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/DBB06886.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/DBB06888.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/DBB06893.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/DBB06894.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/DBB06897.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/DBB06900.webp",
      "/asset/anhweb/hiện đại/12. Biệt thự Oceanpark - Hải Âu 230m2/DBB06903.webp"
    ]
  },
  {
    id: "13-oceanpark-r1-87m2",
    index: "04",
    title: "OCEANPARK R1 87M2",
    tagline: "Dự án • Diện tích: 87 m²2",
    description: "Dự án Oceanpark R1 87m2 mang phong cách hiện đại, được thiết kế với sự tinh tế và tiện nghi tối đa.",
    mainImage: "/asset/anhweb/hiện đại/13. Oceanpark R1 87m2/1-.webp",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách hiện đại.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 87 m²2",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "87 m²2",
    style: "HIEN_DAI",
    gallery: [
      "/asset/anhweb/hiện đại/13. Oceanpark R1 87m2/1-.webp",
      "/asset/anhweb/hiện đại/13. Oceanpark R1 87m2/1.webp",
      "/asset/anhweb/hiện đại/13. Oceanpark R1 87m2/11.webp",
      "/asset/anhweb/hiện đại/13. Oceanpark R1 87m2/13.webp",
      "/asset/anhweb/hiện đại/13. Oceanpark R1 87m2/15.webp",
      "/asset/anhweb/hiện đại/13. Oceanpark R1 87m2/17.webp",
      "/asset/anhweb/hiện đại/13. Oceanpark R1 87m2/19.webp",
      "/asset/anhweb/hiện đại/13. Oceanpark R1 87m2/21.webp",
      "/asset/anhweb/hiện đại/13. Oceanpark R1 87m2/23.webp",
      "/asset/anhweb/hiện đại/13. Oceanpark R1 87m2/25.webp",
      "/asset/anhweb/hiện đại/13. Oceanpark R1 87m2/27.webp",
      "/asset/anhweb/hiện đại/13. Oceanpark R1 87m2/28.webp",
      "/asset/anhweb/hiện đại/13. Oceanpark R1 87m2/3.webp",
      "/asset/anhweb/hiện đại/13. Oceanpark R1 87m2/5.webp",
      "/asset/anhweb/hiện đại/13. Oceanpark R1 87m2/7.webp",
      "/asset/anhweb/hiện đại/13. Oceanpark R1 87m2/9.webp"
    ]
  },
  {
    id: "8-chung-cu-matrix-one-125m2",
    index: "05",
    title: "CHUNG CƯ MATRIX ONE 125M2",
    tagline: "Dự án • Diện tích: 125 m²2",
    description: "Dự án Chung cư Matrix one 125m2 mang phong cách hiện đại, được thiết kế với sự tinh tế và tiện nghi tối đa.",
    mainImage: "/asset/anhweb/hiện đại/8. Chung cư Matrix one 125m2/1.webp",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách hiện đại.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 125 m²2",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "125 m²2",
    style: "HIEN_DAI",
    gallery: [
      "/asset/anhweb/hiện đại/8. Chung cư Matrix one 125m2/1.webp",
      "/asset/anhweb/hiện đại/8. Chung cư Matrix one 125m2/11.webp",
      "/asset/anhweb/hiện đại/8. Chung cư Matrix one 125m2/13.webp",
      "/asset/anhweb/hiện đại/8. Chung cư Matrix one 125m2/15.webp",
      "/asset/anhweb/hiện đại/8. Chung cư Matrix one 125m2/17.webp",
      "/asset/anhweb/hiện đại/8. Chung cư Matrix one 125m2/19.webp",
      "/asset/anhweb/hiện đại/8. Chung cư Matrix one 125m2/21.webp",
      "/asset/anhweb/hiện đại/8. Chung cư Matrix one 125m2/25.webp",
      "/asset/anhweb/hiện đại/8. Chung cư Matrix one 125m2/26.webp",
      "/asset/anhweb/hiện đại/8. Chung cư Matrix one 125m2/7.webp",
      "/asset/anhweb/hiện đại/8. Chung cư Matrix one 125m2/9.webp"
    ]
  },
  {
    id: "9-chung-cu-oceanpark-118m2",
    index: "06",
    title: "CHUNG CƯ OCEANPARK 118M2",
    tagline: "Dự án • Diện tích: 118 m²2",
    description: "Dự án Chung cư OceanPark 118m2 mang phong cách hiện đại, được thiết kế với sự tinh tế và tiện nghi tối đa.",
    mainImage: "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/1.webp",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách hiện đại.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 118 m²2",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "118 m²2",
    style: "HIEN_DAI",
    gallery: [
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/1.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/Phòng khách 1.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/bếp 1.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/bếp 2.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/bếp 3.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/bếp 4.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/bếp 5.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/bếp 6.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/bếp 7.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/mt1.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/mt2.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/mt3.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/ngủ 11.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/ngủ 12.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/phòng khách 2.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/phòng khách 3.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/phòng khách 4.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/phòng khách 5.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/z4640803831715_5eb8295c64aec6799a86921d8b4ce3cf.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/z4640803831718_bac8246dc4b7f861e364d4c7f3a24992.webp",
      "/asset/anhweb/hiện đại/9. Chung cư OceanPark 118m2/z4640803831722_d319be9bd82d62e55447fd51c8e090cf.webp"
    ]
  },
  {
    id: "14-chung-cu-1277-giai-phong-66m2",
    index: "07",
    title: "CHUNG CƯ 1277 GIẢI PHÓNG - 66M2",
    tagline: "Dự án • Diện tích: 66 m²2",
    description: "Dự án Chung cư 1277 Giải Phóng - 66m2 mang phong cách japandi, được thiết kế với sự tinh tế và tiện nghi tối đa.",
    mainImage: "/asset/anhweb/japandi/14. Chung cư 1277 Giải Phóng - 66m2/1.webp",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách japandi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 66 m²2",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "66 m²2",
    style: "JAPANDI",
    gallery: [
      "/asset/anhweb/japandi/14. Chung cư 1277 Giải Phóng - 66m2/1.webp",
      "/asset/anhweb/japandi/14. Chung cư 1277 Giải Phóng - 66m2/11.webp",
      "/asset/anhweb/japandi/14. Chung cư 1277 Giải Phóng - 66m2/13.webp",
      "/asset/anhweb/japandi/14. Chung cư 1277 Giải Phóng - 66m2/15.webp",
      "/asset/anhweb/japandi/14. Chung cư 1277 Giải Phóng - 66m2/17.webp",
      "/asset/anhweb/japandi/14. Chung cư 1277 Giải Phóng - 66m2/19.webp",
      "/asset/anhweb/japandi/14. Chung cư 1277 Giải Phóng - 66m2/21.webp",
      "/asset/anhweb/japandi/14. Chung cư 1277 Giải Phóng - 66m2/23.webp",
      "/asset/anhweb/japandi/14. Chung cư 1277 Giải Phóng - 66m2/25.webp",
      "/asset/anhweb/japandi/14. Chung cư 1277 Giải Phóng - 66m2/3.webp",
      "/asset/anhweb/japandi/14. Chung cư 1277 Giải Phóng - 66m2/5.webp",
      "/asset/anhweb/japandi/14. Chung cư 1277 Giải Phóng - 66m2/7.webp",
      "/asset/anhweb/japandi/14. Chung cư 1277 Giải Phóng - 66m2/9.webp"
    ]
  },
  {
    id: "20-chung-cu-kim-van-kim-lu-70m2",
    index: "08",
    title: "CHUNG CƯ KIM VĂN - KIM LŨ -70M2",
    tagline: "Dự án • Diện tích: 70 m²2",
    description: "Dự án Chung cư Kim văn - Kim lũ -70m2 mang phong cách japandi, được thiết kế với sự tinh tế và tiện nghi tối đa.",
    mainImage: "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/1- kb (1).webp",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách japandi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 70 m²2",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "70 m²2",
    style: "JAPANDI",
    gallery: [
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/1- kb (1).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/1- kb (2).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/1- kb (3).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/1- kb (4).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/1- kb (5).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/1- kb (6).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/1- kb (7).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/2- master (1).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/2- master (2).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/2- master (3).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/2- master (4).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/3- wc master (1).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/3- wc master (2).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/4- ngủ p 1 (1).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/4- ngủ p 1 (2).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/4- ngủ p 1 (3).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/5- ngu p 2 (1).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/5- ngu p 2 (2).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/6- wc chung (1).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/6- wc chung (2).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/7- logia (1).webp",
      "/asset/anhweb/japandi/20. Chung cư Kim văn - Kim lũ -70m2/7- logia (2).webp"
    ]
  },
  {
    id: "4-chung-cu-parkhome-145m2",
    index: "09",
    title: "CHUNG CƯ PARKHOME - 145M2",
    tagline: "Dự án • Diện tích: 145 m²2",
    description: "Dự án Chung cư Parkhome - 145m2 mang phong cách japandi, được thiết kế với sự tinh tế và tiện nghi tối đa.",
    mainImage: "/asset/anhweb/japandi/4. Chung cư Parkhome - 145m2/1.webp",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách japandi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 145 m²2",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "145 m²2",
    style: "JAPANDI",
    gallery: [
      "/asset/anhweb/japandi/4. Chung cư Parkhome - 145m2/1.webp",
      "/asset/anhweb/japandi/4. Chung cư Parkhome - 145m2/11.webp",
      "/asset/anhweb/japandi/4. Chung cư Parkhome - 145m2/12.webp",
      "/asset/anhweb/japandi/4. Chung cư Parkhome - 145m2/13.webp",
      "/asset/anhweb/japandi/4. Chung cư Parkhome - 145m2/14.webp",
      "/asset/anhweb/japandi/4. Chung cư Parkhome - 145m2/15.webp",
      "/asset/anhweb/japandi/4. Chung cư Parkhome - 145m2/16.webp",
      "/asset/anhweb/japandi/4. Chung cư Parkhome - 145m2/17.webp",
      "/asset/anhweb/japandi/4. Chung cư Parkhome - 145m2/2.webp",
      "/asset/anhweb/japandi/4. Chung cư Parkhome - 145m2/3.webp",
      "/asset/anhweb/japandi/4. Chung cư Parkhome - 145m2/4.webp",
      "/asset/anhweb/japandi/4. Chung cư Parkhome - 145m2/5.webp",
      "/asset/anhweb/japandi/4. Chung cư Parkhome - 145m2/6.webp",
      "/asset/anhweb/japandi/4. Chung cư Parkhome - 145m2/7.webp",
      "/asset/anhweb/japandi/4. Chung cư Parkhome - 145m2/8.webp",
      "/asset/anhweb/japandi/4. Chung cư Parkhome - 145m2/9.webp",
      "/asset/anhweb/japandi/4. Chung cư Parkhome - 145m2/Mặt bằng.webp"
    ]
  },
  {
    id: "7-chung-cu-t8-timecity-83m2",
    index: "10",
    title: "CHUNG CƯ T8 - TIMECITY 83M2",
    tagline: "Dự án • Diện tích: 83 m²2",
    description: "Dự án Chung cư T8 - Timecity 83m2 mang phong cách japandi, được thiết kế với sự tinh tế và tiện nghi tối đa.",
    mainImage: "/asset/anhweb/japandi/7. Chung cư T8 - Timecity 83m2/1.webp",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách japandi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 83 m²2",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "83 m²2",
    style: "JAPANDI",
    gallery: [
      "/asset/anhweb/japandi/7. Chung cư T8 - Timecity 83m2/1.webp",
      "/asset/anhweb/japandi/7. Chung cư T8 - Timecity 83m2/10.webp",
      "/asset/anhweb/japandi/7. Chung cư T8 - Timecity 83m2/11.webp",
      "/asset/anhweb/japandi/7. Chung cư T8 - Timecity 83m2/12.webp",
      "/asset/anhweb/japandi/7. Chung cư T8 - Timecity 83m2/13.webp",
      "/asset/anhweb/japandi/7. Chung cư T8 - Timecity 83m2/14.webp",
      "/asset/anhweb/japandi/7. Chung cư T8 - Timecity 83m2/15.webp",
      "/asset/anhweb/japandi/7. Chung cư T8 - Timecity 83m2/2.webp",
      "/asset/anhweb/japandi/7. Chung cư T8 - Timecity 83m2/3.webp",
      "/asset/anhweb/japandi/7. Chung cư T8 - Timecity 83m2/4.webp",
      "/asset/anhweb/japandi/7. Chung cư T8 - Timecity 83m2/5.webp",
      "/asset/anhweb/japandi/7. Chung cư T8 - Timecity 83m2/6.webp",
      "/asset/anhweb/japandi/7. Chung cư T8 - Timecity 83m2/7.webp",
      "/asset/anhweb/japandi/7. Chung cư T8 - Timecity 83m2/8.webp",
      "/asset/anhweb/japandi/7. Chung cư T8 - Timecity 83m2/9.webp",
      "/asset/anhweb/japandi/7. Chung cư T8 - Timecity 83m2/MB.webp"
    ]
  },
  {
    id: "5-shop-my-pham",
    index: "11",
    title: "SHOP MỸ PHẨM",
    tagline: "Dự án • Diện tích: Không xác định",
    description: "Dự án Shop mỹ phẩm mang phong cách shop bán hàng, phòng khám, cửa hàng, được thiết kế với sự tinh tế và tiện nghi tối đa.",
    mainImage: "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/5. Shop mỹ phẩm/1.webp",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách shop bán hàng, phòng khám, cửa hàng.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: Không xác định",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "Không xác định",
    style: "THUONG_MAI",
    gallery: [
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/5. Shop mỹ phẩm/1.webp",
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/5. Shop mỹ phẩm/2.webp",
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/5. Shop mỹ phẩm/3.webp",
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/5. Shop mỹ phẩm/4.webp",
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/5. Shop mỹ phẩm/5.webp",
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/5. Shop mỹ phẩm/6.webp"
    ]
  },
  {
    id: "6-quan-coffe",
    index: "12",
    title: "QUÁN COFFE",
    tagline: "Dự án • Diện tích: Không xác định",
    description: "Dự án Quán coffe mang phong cách shop bán hàng, phòng khám, cửa hàng, được thiết kế với sự tinh tế và tiện nghi tối đa.",
    mainImage: "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/6. Quán coffe/1.webp",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách shop bán hàng, phòng khám, cửa hàng.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: Không xác định",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "Không xác định",
    style: "THUONG_MAI",
    gallery: [
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/6. Quán coffe/1.webp",
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/6. Quán coffe/10.webp",
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/6. Quán coffe/11.webp",
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/6. Quán coffe/12.webp",
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/6. Quán coffe/13.webp",
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/6. Quán coffe/14.webp",
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/6. Quán coffe/2.webp",
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/6. Quán coffe/3.webp",
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/6. Quán coffe/4.webp",
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/6. Quán coffe/5.webp",
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/6. Quán coffe/6.webp",
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/6. Quán coffe/7.webp",
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/6. Quán coffe/8.webp",
      "/asset/anhweb/shop bán hàng, phòng khám, cửa hàng/6. Quán coffe/9.webp"
    ]
  },
  {
    id: "17-nha-pho-5x20-3-tang-thanh-hoa",
    index: "13",
    title: "NHÀ PHỐ - 5X20 3 TẦNG - THANH HÓA",
    tagline: "Dự án • Diện tích: 5x20",
    description: "Dự án Nhà phố - 5x20 3 tầng - Thanh Hóa mang phong cách wabi-sabi, được thiết kế với sự tinh tế và tiện nghi tối đa.",
    mainImage: "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/1.webp",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách wabi-sabi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Thanh Hóa",
      "Diện tích: 5x20",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Thanh Hóa",
    area: "5x20",
    style: "WABISABI",
    gallery: [
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/1.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/11-2.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/13.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/15.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/17.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/20.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/22.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/24.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/26.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/28.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/3.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/30.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/32.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/34.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/36.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/38.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/40.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/42.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/44.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/46.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/5.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/7.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/9.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/MT1.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/MT2.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/MT3.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/MT4.webp",
      "/asset/anhweb/wabi-sabi/17. Nhà phố - 5x20 3 tầng - Thanh Hóa/MT5.webp"
    ]
  },
  {
    id: "19-chung-cu-royal-city-128m2",
    index: "14",
    title: "CHUNG CƯ ROYAL CITY 128M2",
    tagline: "Dự án • Diện tích: 128 m²2",
    description: "Dự án Chung cư Royal City 128m2 mang phong cách wabi-sabi, được thiết kế với sự tinh tế và tiện nghi tối đa.",
    mainImage: "/asset/anhweb/wabi-sabi/19. Chung cư Royal City 128m2/1.webp",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách wabi-sabi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 128 m²2",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "128 m²2",
    style: "WABISABI",
    gallery: [
      "/asset/anhweb/wabi-sabi/19. Chung cư Royal City 128m2/1.webp",
      "/asset/anhweb/wabi-sabi/19. Chung cư Royal City 128m2/10.webp",
      "/asset/anhweb/wabi-sabi/19. Chung cư Royal City 128m2/11.webp",
      "/asset/anhweb/wabi-sabi/19. Chung cư Royal City 128m2/12.webp",
      "/asset/anhweb/wabi-sabi/19. Chung cư Royal City 128m2/13.webp",
      "/asset/anhweb/wabi-sabi/19. Chung cư Royal City 128m2/14.webp",
      "/asset/anhweb/wabi-sabi/19. Chung cư Royal City 128m2/15.webp",
      "/asset/anhweb/wabi-sabi/19. Chung cư Royal City 128m2/16.webp",
      "/asset/anhweb/wabi-sabi/19. Chung cư Royal City 128m2/17.webp",
      "/asset/anhweb/wabi-sabi/19. Chung cư Royal City 128m2/2.webp",
      "/asset/anhweb/wabi-sabi/19. Chung cư Royal City 128m2/3.webp",
      "/asset/anhweb/wabi-sabi/19. Chung cư Royal City 128m2/4.webp",
      "/asset/anhweb/wabi-sabi/19. Chung cư Royal City 128m2/5.webp",
      "/asset/anhweb/wabi-sabi/19. Chung cư Royal City 128m2/6.webp",
      "/asset/anhweb/wabi-sabi/19. Chung cư Royal City 128m2/7.webp",
      "/asset/anhweb/wabi-sabi/19. Chung cư Royal City 128m2/8.webp",
      "/asset/anhweb/wabi-sabi/19. Chung cư Royal City 128m2/9.webp"
    ]
  },
  {
    id: "22-chung-cu-gs1-vin-smart-45m2",
    index: "15",
    title: "CHUNG CƯ GS1 VIN SMART 45M2",
    tagline: "Dự án • Diện tích: 45 m²2",
    description: "Dự án Chung cư GS1 Vin Smart 45m2 mang phong cách wabi-sabi, được thiết kế với sự tinh tế và tiện nghi tối đa.",
    mainImage: "/asset/anhweb/wabi-sabi/22. Chung cư GS1 Vin Smart 45m2/1.webp",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách wabi-sabi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 45 m²2",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "45 m²2",
    style: "WABISABI",
    gallery: [
      "/asset/anhweb/wabi-sabi/22. Chung cư GS1 Vin Smart 45m2/1.webp",
      "/asset/anhweb/wabi-sabi/22. Chung cư GS1 Vin Smart 45m2/10.webp",
      "/asset/anhweb/wabi-sabi/22. Chung cư GS1 Vin Smart 45m2/11.webp",
      "/asset/anhweb/wabi-sabi/22. Chung cư GS1 Vin Smart 45m2/12.webp",
      "/asset/anhweb/wabi-sabi/22. Chung cư GS1 Vin Smart 45m2/2.webp",
      "/asset/anhweb/wabi-sabi/22. Chung cư GS1 Vin Smart 45m2/3.webp",
      "/asset/anhweb/wabi-sabi/22. Chung cư GS1 Vin Smart 45m2/4.webp",
      "/asset/anhweb/wabi-sabi/22. Chung cư GS1 Vin Smart 45m2/5.webp",
      "/asset/anhweb/wabi-sabi/22. Chung cư GS1 Vin Smart 45m2/6.webp",
      "/asset/anhweb/wabi-sabi/22. Chung cư GS1 Vin Smart 45m2/7.webp",
      "/asset/anhweb/wabi-sabi/22. Chung cư GS1 Vin Smart 45m2/8.webp",
      "/asset/anhweb/wabi-sabi/22. Chung cư GS1 Vin Smart 45m2/9.webp"
    ]
  },
  {
    id: "23-nha-at-ien-bien-130m2",
    index: "16",
    title: "NHÀ ĐẤT ĐIỆN BIÊN 130M2",
    tagline: "Dự án • Diện tích: 130 m²2",
    description: "Dự án Nhà đất Điện Biên 130m2 mang phong cách wabi-sabi, được thiết kế với sự tinh tế và tiện nghi tối đa.",
    mainImage: "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (1).webp",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách wabi-sabi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Điện Biên",
      "Diện tích: 130 m²2",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Điện Biên",
    area: "130 m²2",
    style: "WABISABI",
    gallery: [
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (1).webp",
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (10).webp",
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (11).webp",
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (12).webp",
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (13).webp",
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (14).webp",
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (15).webp",
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (16).webp",
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (17).webp",
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (18).webp",
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (19).webp",
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (2).webp",
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (20).webp",
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (3).webp",
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (4).webp",
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (5).webp",
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (6).webp",
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (7).webp",
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (8).webp",
      "/asset/anhweb/wabi-sabi/23. Nhà đất Điện Biên 130m2/kb (9).webp"
    ]
  },
  {
    id: "3-chung-cu-115-m2",
    index: "17",
    title: "CHUNG CƯ 115 M2",
    tagline: "Dự án • Diện tích: 115  m²2",
    description: "Dự án Chung cư 115 m2 mang phong cách wabi-sabi, được thiết kế với sự tinh tế và tiện nghi tối đa.",
    mainImage: "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/1.webp",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách wabi-sabi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 115  m²2",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "115  m²2",
    style: "WABISABI",
    gallery: [
      "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/1.webp",
      "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/10.webp",
      "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/11.webp",
      "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/12.webp",
      "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/13.webp",
      "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/14.webp",
      "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/15.webp",
      "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/16.webp",
      "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/17.webp",
      "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/18.webp",
      "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/19.webp",
      "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/2.webp",
      "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/3.webp",
      "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/4.webp",
      "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/5.webp",
      "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/6.webp",
      "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/7.webp",
      "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/8.webp",
      "/asset/anhweb/wabi-sabi/3. Chung cư 115 m2/mb.webp"
    ]
  }
];
