import { Project } from '../types';

export const projects: Project[] = [
  {
    id: "10-cai-tao-nha-lao-cai-4-3x19",
    index: "01",
    title: "CẢI TẠO NHÀ LÀO CAI 4.3x19",
    tagline: "Dự án • Diện tích: 4.3x19",
    description: "Thiết kế khai thác lợi thế chiều cao trần tại khu vực trung tâm, kết hợp vách đá Marble tự nhiên cao kịch trần để kiến tạo cấu trúc bề thế. Sự kết nối giữa các tầng được duy trì bằng hệ lan can kính kiến trúc cường lực, xóa bỏ mọi rào cản thị giác. Toàn bộ thiết bị thông minh (Smart-home) và hệ thống điều hòa trung tâm được giấu kín tinh tế, ưu tiên không gian cho các diện tường kính lớn hướng tầm nhìn ra mảng xanh ngoại cảnh.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách hiện đại.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Lào Cai",
      "Diện tích: 4.3x19",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Lào Cai",
    area: "4.3x19",
    style: "HIEN_DAI",
    mainImage: "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-1-1.webp",
    gallery: [
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/master-8.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/ngu-phu-1.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/ngu-phu-2.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/p-tho.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/sanh.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-3-1.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-3-2.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-3-3.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-3-4.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-3-5.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-3-6.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-3-7.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-3-8.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-3-9.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-1-1.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-1-10.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-1-11.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-1-12.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-1-13.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-1-2.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-1-3.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-1-4.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-1-5.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-1-6.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-1-7.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-1-8.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-1-9.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-2-1.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-2-2.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-2-3.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-2-4.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-2-5.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-2-6.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-2-7.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-2-8.webp",
      "/asset/anhweb/hien-dai/10-cai-tao-nha-lao-cai-43x19/tang-2-9.webp"
    ]
  },
  {
    id: "11-chung-cu-masteri-72m2",
    index: "02",
    title: "CHUNG CƯ MASTERI 72m²",
    tagline: "Dự án • Diện tích: 72 m²",
    description: "Phương án ứng dụng giải pháp bố trí không gian mở liên hoàn (Open-plan concept) giữa Khách - Bếp - Ăn nhằm nhân đôi cảm giác rộng rãi. Điểm chạm thị giác được xử lý bằng các vật liệu có tính phản chiếu cao như kính xám khói, nẹp kim loại titan và đá nung kết (Sintered Stone) vân lớn. Hệ thống ánh sáng được kịch bản hóa (Lighting scenario) với các dải LED âm trần định hình tuyến tính, biến căn hộ thành một không gian lounge sang trọng vào ban đêm.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách hiện đại.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 72 m²",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "72 m²",
    style: "HIEN_DAI",
    mainImage: "/asset/anhweb/hien-dai/11-chung-cu-masteri-72m2/11.webp",
    gallery: [
      "/asset/anhweb/hien-dai/11-chung-cu-masteri-72m2/11.webp",
      "/asset/anhweb/hien-dai/11-chung-cu-masteri-72m2/13.webp",
      "/asset/anhweb/hien-dai/11-chung-cu-masteri-72m2/15.webp",
      "/asset/anhweb/hien-dai/11-chung-cu-masteri-72m2/17.webp",
      "/asset/anhweb/hien-dai/11-chung-cu-masteri-72m2/19.webp",
      "/asset/anhweb/hien-dai/11-chung-cu-masteri-72m2/21.webp",
      "/asset/anhweb/hien-dai/11-chung-cu-masteri-72m2/3.webp",
      "/asset/anhweb/hien-dai/11-chung-cu-masteri-72m2/5.webp",
      "/asset/anhweb/hien-dai/11-chung-cu-masteri-72m2/7.webp",
      "/asset/anhweb/hien-dai/11-chung-cu-masteri-72m2/9.webp"
    ]
  },
  {
    id: "12-biet-thu-oceanpark-hai-au-230m2",
    index: "03",
    title: "BIỆT THỰ OCEANPARK - HẢI ÂU 230m²",
    tagline: "Dự án • Diện tích: 230 m²",
    description: "Thiết kế khai thác lợi thế chiều cao trần tại khu vực trung tâm, kết hợp vách đá Marble tự nhiên cao kịch trần để kiến tạo cấu trúc bề thế. Sự kết nối giữa các tầng được duy trì bằng hệ lan can kính kiến trúc cường lực, xóa bỏ mọi rào cản thị giác. Toàn bộ thiết bị thông minh (Smart-home) và hệ thống điều hòa trung tâm được giấu kín tinh tế, ưu tiên không gian cho các diện tường kính lớn hướng tầm nhìn ra mảng xanh ngoại cảnh.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách hiện đại.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 230 m²",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "230 m²",
    style: "HIEN_DAI",
    mainImage: "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/3.webp",
    gallery: [
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/1.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/10.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/11.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/12.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/13.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/131.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/14.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/15.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/16.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/17.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/18.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/19.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/2.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/20.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/21.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/22.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/23.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/24.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/25.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/26.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/27.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/28.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/29.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/3.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/30.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/31.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/4.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/5.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/6.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/7.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/8.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/9.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/dbb06886.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/dbb06888.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/dbb06893.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/dbb06894.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/dbb06897.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/dbb06900.webp",
      "/asset/anhweb/hien-dai/12-biet-thu-oceanpark-hai-au-230m2/dbb06903.webp"
    ]
  },
  {
    id: "13-oceanpark-r1-87m2",
    index: "04",
    title: "OCEANPARK R1 87m²",
    tagline: "Dự án • Diện tích: 87 m²",
    description: "Thiết kế khai thác lợi thế chiều cao trần tại khu vực trung tâm, kết hợp vách đá Marble tự nhiên cao kịch trần để kiến tạo cấu trúc bề thế. Sự kết nối giữa các tầng được duy trì bằng hệ lan can kính kiến trúc cường lực, xóa bỏ mọi rào cản thị giác. Toàn bộ thiết bị thông minh (Smart-home) và hệ thống điều hòa trung tâm được giấu kín tinh tế, ưu tiên không gian cho các diện tường kính lớn hướng tầm nhìn ra mảng xanh ngoại cảnh.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách hiện đại.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 87 m²",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "87 m²",
    style: "HIEN_DAI",
    mainImage: "/asset/anhweb/hien-dai/13-oceanpark-r1-87m2/3.webp",
    gallery: [
      "/asset/anhweb/hien-dai/13-oceanpark-r1-87m2/11.webp",
      "/asset/anhweb/hien-dai/13-oceanpark-r1-87m2/13.webp",
      "/asset/anhweb/hien-dai/13-oceanpark-r1-87m2/15.webp",
      "/asset/anhweb/hien-dai/13-oceanpark-r1-87m2/17.webp",
      "/asset/anhweb/hien-dai/13-oceanpark-r1-87m2/19.webp",
      "/asset/anhweb/hien-dai/13-oceanpark-r1-87m2/21.webp",
      "/asset/anhweb/hien-dai/13-oceanpark-r1-87m2/23.webp",
      "/asset/anhweb/hien-dai/13-oceanpark-r1-87m2/25.webp",
      "/asset/anhweb/hien-dai/13-oceanpark-r1-87m2/27.webp",
      "/asset/anhweb/hien-dai/13-oceanpark-r1-87m2/28.webp",
      "/asset/anhweb/hien-dai/13-oceanpark-r1-87m2/3.webp",
      "/asset/anhweb/hien-dai/13-oceanpark-r1-87m2/5.webp",
      "/asset/anhweb/hien-dai/13-oceanpark-r1-87m2/7.webp",
      "/asset/anhweb/hien-dai/13-oceanpark-r1-87m2/9.webp"
    ]
  },
  {
    id: "8-chung-cu-matrix-one-125m2",
    index: "05",
    title: "CHUNG CƯ MATRIX ONE 125m²",
    tagline: "Dự án • Diện tích: 125 m²",
    description: "Phương án ứng dụng giải pháp bố trí không gian mở liên hoàn (Open-plan concept) giữa Khách - Bếp - Ăn nhằm nhân đôi cảm giác rộng rãi. Điểm chạm thị giác được xử lý bằng các vật liệu có tính phản chiếu cao như kính xám khói, nẹp kim loại titan và đá nung kết (Sintered Stone) vân lớn. Hệ thống ánh sáng được kịch bản hóa (Lighting scenario) với các dải LED âm trần định hình tuyến tính, biến căn hộ thành một không gian lounge sang trọng vào ban đêm.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách hiện đại.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 125 m²",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "125 m²",
    style: "HIEN_DAI",
    mainImage: "/asset/anhweb/hien-dai/8-chung-cu-matrix-one-125m2/11.webp",
    gallery: [
      "/asset/anhweb/hien-dai/8-chung-cu-matrix-one-125m2/11.webp",
      "/asset/anhweb/hien-dai/8-chung-cu-matrix-one-125m2/13.webp",
      "/asset/anhweb/hien-dai/8-chung-cu-matrix-one-125m2/15.webp",
      "/asset/anhweb/hien-dai/8-chung-cu-matrix-one-125m2/17.webp",
      "/asset/anhweb/hien-dai/8-chung-cu-matrix-one-125m2/19.webp",
      "/asset/anhweb/hien-dai/8-chung-cu-matrix-one-125m2/21.webp",
      "/asset/anhweb/hien-dai/8-chung-cu-matrix-one-125m2/25.webp",
      "/asset/anhweb/hien-dai/8-chung-cu-matrix-one-125m2/26.webp",
      "/asset/anhweb/hien-dai/8-chung-cu-matrix-one-125m2/7.webp",
      "/asset/anhweb/hien-dai/8-chung-cu-matrix-one-125m2/9.webp"
    ]
  },
  {
    id: "9-chung-cu-oceanpark-118m2",
    index: "06",
    title: "CHUNG CƯ OCEANPARK 118m²",
    tagline: "Dự án • Diện tích: 118 m²",
    description: "Phương án ứng dụng giải pháp bố trí không gian mở liên hoàn (Open-plan concept) giữa Khách - Bếp - Ăn nhằm nhân đôi cảm giác rộng rãi. Điểm chạm thị giác được xử lý bằng các vật liệu có tính phản chiếu cao như kính xám khói, nẹp kim loại titan và đá nung kết (Sintered Stone) vân lớn. Hệ thống ánh sáng được kịch bản hóa (Lighting scenario) với các dải LED âm trần định hình tuyến tính, biến căn hộ thành một không gian lounge sang trọng vào ban đêm.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách hiện đại.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 118 m²",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "118 m²",
    style: "HIEN_DAI",
    mainImage: "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/phong-khach-1.webp",
    gallery: [
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/phong-khach-1.webp",
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/phong-khach-2.webp",
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/phong-khach-3.webp",
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/phong-khach-4.webp",
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/phong-khach-5.webp",
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/bep-1.webp",
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/bep-2.webp",
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/bep-3.webp",
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/bep-4.webp",
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/bep-5.webp",
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/bep-6.webp",
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/bep-7.webp",
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/mt1.webp",
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/mt2.webp",
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/mt3.webp",
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/ngu-11.webp",
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/ngu-12.webp",
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/z4640803831715_5eb8295c64aec6799a86921d8b4ce3cf.webp",
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/z4640803831718_bac8246dc4b7f861e364d4c7f3a24992.webp",
      "/asset/anhweb/hien-dai/9-chung-cu-oceanpark-118m2/z4640803831722_d319be9bd82d62e55447fd51c8e090cf.webp"
    ]
  },
  {
    id: "14-chung-cu-1277-giai-phong-66m2",
    index: "07",
    title: "CHUNG CƯ 1277 GIẢI PHÓNG - 66m²",
    tagline: "Dự án • Diện tích: 66 m²",
    description: "Thiết kế tập trung vào việc giải phóng diện tích sàn bằng hệ nội thất chân thanh mảnh và các cấu kiện gỗ sồi (Oak) màu sáng. Sự kết hợp giữa sắc trắng tràm của Bắc Âu và chất liệu mây tre đan truyền thống Nhật Bản tạo nên bộ lọc thị giác nhẹ nhàng. Hệ tủ lưu trữ được thiết kế kịch trần, phẳng mặt (Handleless) biến công năng lưu trữ thành những mảng tường vô hình, tối đa hóa khoảng thở cho căn hộ diện tích nhỏ.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách japandi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 66 m²",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "66 m²",
    style: "JAPANDI",
    mainImage: "/asset/anhweb/japandi/14-chung-cu-1277-giai-phong-66m2/1.webp",
    gallery: [
      "/asset/anhweb/japandi/14-chung-cu-1277-giai-phong-66m2/1.webp",
      "/asset/anhweb/japandi/14-chung-cu-1277-giai-phong-66m2/11.webp",
      "/asset/anhweb/japandi/14-chung-cu-1277-giai-phong-66m2/13.webp",
      "/asset/anhweb/japandi/14-chung-cu-1277-giai-phong-66m2/15.webp",
      "/asset/anhweb/japandi/14-chung-cu-1277-giai-phong-66m2/17.webp",
      "/asset/anhweb/japandi/14-chung-cu-1277-giai-phong-66m2/19.webp",
      "/asset/anhweb/japandi/14-chung-cu-1277-giai-phong-66m2/21.webp",
      "/asset/anhweb/japandi/14-chung-cu-1277-giai-phong-66m2/23.webp",
      "/asset/anhweb/japandi/14-chung-cu-1277-giai-phong-66m2/25.webp",
      "/asset/anhweb/japandi/14-chung-cu-1277-giai-phong-66m2/3.webp",
      "/asset/anhweb/japandi/14-chung-cu-1277-giai-phong-66m2/5.webp",
      "/asset/anhweb/japandi/14-chung-cu-1277-giai-phong-66m2/7.webp",
      "/asset/anhweb/japandi/14-chung-cu-1277-giai-phong-66m2/9.webp"
    ]
  },
  {
    id: "20-chung-cu-kim-van-kim-lu-70m2",
    index: "08",
    title: "CHUNG CƯ KIM VĂN - KIM LŨ -70m²",
    tagline: "Dự án • Diện tích: 70 m²",
    description: "Thiết kế tập trung vào việc giải phóng diện tích sàn bằng hệ nội thất chân thanh mảnh và các cấu kiện gỗ sồi (Oak) màu sáng. Sự kết hợp giữa sắc trắng tràm của Bắc Âu và chất liệu mây tre đan truyền thống Nhật Bản tạo nên bộ lọc thị giác nhẹ nhàng. Hệ tủ lưu trữ được thiết kế kịch trần, phẳng mặt (Handleless) biến công năng lưu trữ thành những mảng tường vô hình, tối đa hóa khoảng thở cho căn hộ diện tích nhỏ.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách japandi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 70 m²",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "70 m²",
    style: "JAPANDI",
    mainImage: "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/1-kb-1.webp",
    gallery: [
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/1-kb-1.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/1-kb-2.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/1-kb-3.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/1-kb-4.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/1-kb-5.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/1-kb-6.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/1-kb-7.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/2-master-1.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/2-master-2.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/2-master-3.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/2-master-4.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/3-wc-master-1.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/3-wc-master-2.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/4-ngu-p-1-1.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/4-ngu-p-1-2.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/4-ngu-p-1-3.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/5-ngu-p-2-1.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/5-ngu-p-2-2.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/6-wc-chung-1.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/6-wc-chung-2.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/7-logia-1.webp",
      "/asset/anhweb/japandi/20-chung-cu-kim-van-kim-lu-70m2/7-logia-2.webp"
    ]
  },
  {
    id: "4-chung-cu-parkhome-145m2",
    index: "09",
    title: "CHUNG CƯ PARKHOME - 145m²",
    tagline: "Dự án • Diện tích: 145 m²",
    description: "Thiết kế tập trung vào việc giải phóng diện tích sàn bằng hệ nội thất chân thanh mảnh và các cấu kiện gỗ sồi (Oak) màu sáng. Sự kết hợp giữa sắc trắng tràm của Bắc Âu và chất liệu mây tre đan truyền thống Nhật Bản tạo nên bộ lọc thị giác nhẹ nhàng. Hệ tủ lưu trữ được thiết kế kịch trần, phẳng mặt (Handleless) biến công năng lưu trữ thành những mảng tường vô hình, tối đa hóa khoảng thở cho căn hộ diện tích nhỏ.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách japandi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 145 m²",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "145 m²",
    style: "JAPANDI",
    mainImage: "/asset/anhweb/japandi/4-chung-cu-parkhome-145m2/1.webp",
    gallery: [
      "/asset/anhweb/japandi/4-chung-cu-parkhome-145m2/1.webp",
      "/asset/anhweb/japandi/4-chung-cu-parkhome-145m2/11.webp",
      "/asset/anhweb/japandi/4-chung-cu-parkhome-145m2/12.webp",
      "/asset/anhweb/japandi/4-chung-cu-parkhome-145m2/13.webp",
      "/asset/anhweb/japandi/4-chung-cu-parkhome-145m2/14.webp",
      "/asset/anhweb/japandi/4-chung-cu-parkhome-145m2/15.webp",
      "/asset/anhweb/japandi/4-chung-cu-parkhome-145m2/16.webp",
      "/asset/anhweb/japandi/4-chung-cu-parkhome-145m2/17.webp",
      "/asset/anhweb/japandi/4-chung-cu-parkhome-145m2/2.webp",
      "/asset/anhweb/japandi/4-chung-cu-parkhome-145m2/3.webp",
      "/asset/anhweb/japandi/4-chung-cu-parkhome-145m2/4.webp",
      "/asset/anhweb/japandi/4-chung-cu-parkhome-145m2/5.webp",
      "/asset/anhweb/japandi/4-chung-cu-parkhome-145m2/6.webp",
      "/asset/anhweb/japandi/4-chung-cu-parkhome-145m2/7.webp",
      "/asset/anhweb/japandi/4-chung-cu-parkhome-145m2/8.webp",
      "/asset/anhweb/japandi/4-chung-cu-parkhome-145m2/9.webp"
    ]
  },
  {
    id: "7-chung-cu-t8-timecity-83m2",
    index: "10",
    title: "CHUNG CƯ T8 - TIMECITY 83m²",
    tagline: "Dự án • Diện tích: 83 m²",
    description: "Thiết kế tập trung vào việc giải phóng diện tích sàn bằng hệ nội thất chân thanh mảnh và các cấu kiện gỗ sồi (Oak) màu sáng. Sự kết hợp giữa sắc trắng tràm của Bắc Âu và chất liệu mây tre đan truyền thống Nhật Bản tạo nên bộ lọc thị giác nhẹ nhàng. Hệ tủ lưu trữ được thiết kế kịch trần, phẳng mặt (Handleless) biến công năng lưu trữ thành những mảng tường vô hình, tối đa hóa khoảng thở cho căn hộ diện tích nhỏ.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách japandi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 83 m²",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "83 m²",
    style: "JAPANDI",
    mainImage: "/asset/anhweb/japandi/7-chung-cu-t8-timecity-83m2/1.webp",
    gallery: [
      "/asset/anhweb/japandi/7-chung-cu-t8-timecity-83m2/1.webp",
      "/asset/anhweb/japandi/7-chung-cu-t8-timecity-83m2/10.webp",
      "/asset/anhweb/japandi/7-chung-cu-t8-timecity-83m2/11.webp",
      "/asset/anhweb/japandi/7-chung-cu-t8-timecity-83m2/12.webp",
      "/asset/anhweb/japandi/7-chung-cu-t8-timecity-83m2/13.webp",
      "/asset/anhweb/japandi/7-chung-cu-t8-timecity-83m2/14.webp",
      "/asset/anhweb/japandi/7-chung-cu-t8-timecity-83m2/15.webp",
      "/asset/anhweb/japandi/7-chung-cu-t8-timecity-83m2/2.webp",
      "/asset/anhweb/japandi/7-chung-cu-t8-timecity-83m2/3.webp",
      "/asset/anhweb/japandi/7-chung-cu-t8-timecity-83m2/4.webp",
      "/asset/anhweb/japandi/7-chung-cu-t8-timecity-83m2/5.webp",
      "/asset/anhweb/japandi/7-chung-cu-t8-timecity-83m2/6.webp",
      "/asset/anhweb/japandi/7-chung-cu-t8-timecity-83m2/7.webp",
      "/asset/anhweb/japandi/7-chung-cu-t8-timecity-83m2/8.webp",
      "/asset/anhweb/japandi/7-chung-cu-t8-timecity-83m2/9.webp"
    ]
  },
  {
    id: "5-shop-my-pham",
    index: "11",
    title: "SHOP MỸ PHẨM",
    tagline: "Dự án • Diện tích: Không xác định",
    description: "Dự án Shop mỹ phẩm mang phong cách shop bán hàng, phòng khám, cửa hàng, được thiết kế với sự tinh tế và tiện nghi tối đa.",
    mainImage: "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/5-shop-my-pham/1.webp",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách shop bán hàng, phòng khám, cửa hàng.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: Không xác định",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "Không xác định",
    style: "THUONG_MAI",
    gallery: [
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/5-shop-my-pham/1.webp",
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/5-shop-my-pham/2.webp",
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/5-shop-my-pham/3.webp",
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/5-shop-my-pham/4.webp",
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/5-shop-my-pham/5.webp",
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/5-shop-my-pham/6.webp"
    ]
  },
  {
    id: "6-quan-coffe",
    index: "12",
    title: "QUÁN COFFE",
    tagline: "Dự án • Diện tích: Không xác định",
    description: "Dự án Quán coffe mang phong cách shop bán hàng, phòng khám, cửa hàng, được thiết kế với sự tinh tế và tiện nghi tối đa.",
    mainImage: "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/6-quan-coffe/1.webp",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách shop bán hàng, phòng khám, cửa hàng.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: Không xác định",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "Không xác định",
    style: "THUONG_MAI",
    gallery: [
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/6-quan-coffe/1.webp",
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/6-quan-coffe/10.webp",
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/6-quan-coffe/11.webp",
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/6-quan-coffe/12.webp",
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/6-quan-coffe/13.webp",
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/6-quan-coffe/14.webp",
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/6-quan-coffe/2.webp",
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/6-quan-coffe/3.webp",
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/6-quan-coffe/4.webp",
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/6-quan-coffe/5.webp",
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/6-quan-coffe/6.webp",
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/6-quan-coffe/7.webp",
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/6-quan-coffe/8.webp",
      "/asset/anhweb/shop-ban-hang-phong-kham-cua-hang/6-quan-coffe/9.webp"
    ]
  },
  {
    id: "17-nha-pho-5x20-3-tang-thanh-hoa",
    index: "13",
    title: "NHÀ PHỐ - 5x20 3 TẦNG - THANH HÓA",
    tagline: "Dự án • Diện tích: 5x20",
    description: "Thiết kế tôn vinh tính nguyên bản của vật liệu thông qua các hệ dầm gỗ thô nguyên khối để lộ vân nứt tự nhiên, kết hợp với sàn đá mài (Terrazzo) hạt lớn. Không gian áp dụng nghệ thuật sắp đặt ánh sáng Chiaroscuro (Tương phản sáng - tối), tạo ra những khoảng tối tĩnh lặng xen kẽ những vệt nắng đổ từ giếng trời. Sự hiện diện của một tiểu cảnh tĩnh (vườn khô Zen) đặt tại giếng trời đóng vai trò là lõi năng lượng, kết nối ngôi nhà trực tiếp với các yếu tố tự nhiên: Nước, Đá, Gỗ và Không khí.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách wabi-sabi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Thanh Hóa",
      "Diện tích: 5x20",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Thanh Hóa",
    area: "5x20",
    style: "WABISABI",
    mainImage: "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/1.webp",
    gallery: [
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/1.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/11-2.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/13.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/15.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/17.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/20.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/22.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/24.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/26.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/28.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/3.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/30.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/32.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/34.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/36.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/38.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/40.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/42.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/44.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/46.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/5.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/7.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/9.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/mt1.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/mt2.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/mt3.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/mt4.webp",
      "/asset/anhweb/wabi-sabi/17-nha-pho-5x20-3-tang-thanh-hoa/mt5.webp"
    ]
  },
  {
    id: "19-chung-cu-royal-city-128m2",
    index: "14",
    title: "CHUNG CƯ ROYAL CITY 128m²",
    tagline: "Dự án • Diện tích: 128 m²",
    description: "Chúng tôi tiến hành mềm hóa cấu trúc thô cứng của căn hộ bằng các hệ trần và hốc tường bo cong (Curved architecture). Toàn bộ bề mặt tường được phủ sơn hiệu ứng vi xi măng (Microcement) hoặc sơn đất sét với bề mặt gai nhẹ, hấp thụ ánh sáng một cách khuếch tán, triệt tiêu sự bóng bẩy. Nội thất ưu tiên các hình khối hữu cơ (Organic shapes), sofa vải thô tự nhiên (Bouclé) mang tông màu của đất và cát, tạo ra một ốc đảo tĩnh lặng tách biệt khỏi nhịp sống đô thị.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách wabi-sabi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 128 m²",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "128 m²",
    style: "WABISABI",
    mainImage: "/asset/anhweb/wabi-sabi/19-chung-cu-royal-city-128m2/1.webp",
    gallery: [
      "/asset/anhweb/wabi-sabi/19-chung-cu-royal-city-128m2/1.webp",
      "/asset/anhweb/wabi-sabi/19-chung-cu-royal-city-128m2/10.webp",
      "/asset/anhweb/wabi-sabi/19-chung-cu-royal-city-128m2/11.webp",
      "/asset/anhweb/wabi-sabi/19-chung-cu-royal-city-128m2/12.webp",
      "/asset/anhweb/wabi-sabi/19-chung-cu-royal-city-128m2/13.webp",
      "/asset/anhweb/wabi-sabi/19-chung-cu-royal-city-128m2/14.webp",
      "/asset/anhweb/wabi-sabi/19-chung-cu-royal-city-128m2/15.webp",
      "/asset/anhweb/wabi-sabi/19-chung-cu-royal-city-128m2/16.webp",
      "/asset/anhweb/wabi-sabi/19-chung-cu-royal-city-128m2/17.webp",
      "/asset/anhweb/wabi-sabi/19-chung-cu-royal-city-128m2/2.webp",
      "/asset/anhweb/wabi-sabi/19-chung-cu-royal-city-128m2/3.webp",
      "/asset/anhweb/wabi-sabi/19-chung-cu-royal-city-128m2/4.webp",
      "/asset/anhweb/wabi-sabi/19-chung-cu-royal-city-128m2/5.webp",
      "/asset/anhweb/wabi-sabi/19-chung-cu-royal-city-128m2/6.webp",
      "/asset/anhweb/wabi-sabi/19-chung-cu-royal-city-128m2/7.webp",
      "/asset/anhweb/wabi-sabi/19-chung-cu-royal-city-128m2/8.webp",
      "/asset/anhweb/wabi-sabi/19-chung-cu-royal-city-128m2/9.webp"
    ]
  },
  {
    id: "22-chung-cu-gs1-vin-smart-45m2",
    index: "15",
    title: "CHUNG CƯ GS1 VIN SMART 45m²",
    tagline: "Dự án • Diện tích: 45 m²",
    description: "Chúng tôi tiến hành mềm hóa cấu trúc thô cứng của căn hộ bằng các hệ trần và hốc tường bo cong (Curved architecture). Toàn bộ bề mặt tường được phủ sơn hiệu ứng vi xi măng (Microcement) hoặc sơn đất sét với bề mặt gai nhẹ, hấp thụ ánh sáng một cách khuếch tán, triệt tiêu sự bóng bẩy. Nội thất ưu tiên các hình khối hữu cơ (Organic shapes), sofa vải thô tự nhiên (Bouclé) mang tông màu của đất và cát, tạo ra một ốc đảo tĩnh lặng tách biệt khỏi nhịp sống đô thị.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách wabi-sabi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 45 m²",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "45 m²",
    style: "WABISABI",
    mainImage: "/asset/anhweb/wabi-sabi/22-chung-cu-gs1-vin-smart-45m2/1.webp",
    gallery: [
      "/asset/anhweb/wabi-sabi/22-chung-cu-gs1-vin-smart-45m2/1.webp",
      "/asset/anhweb/wabi-sabi/22-chung-cu-gs1-vin-smart-45m2/10.webp",
      "/asset/anhweb/wabi-sabi/22-chung-cu-gs1-vin-smart-45m2/11.webp",
      "/asset/anhweb/wabi-sabi/22-chung-cu-gs1-vin-smart-45m2/12.webp",
      "/asset/anhweb/wabi-sabi/22-chung-cu-gs1-vin-smart-45m2/2.webp",
      "/asset/anhweb/wabi-sabi/22-chung-cu-gs1-vin-smart-45m2/3.webp",
      "/asset/anhweb/wabi-sabi/22-chung-cu-gs1-vin-smart-45m2/4.webp",
      "/asset/anhweb/wabi-sabi/22-chung-cu-gs1-vin-smart-45m2/5.webp",
      "/asset/anhweb/wabi-sabi/22-chung-cu-gs1-vin-smart-45m2/6.webp",
      "/asset/anhweb/wabi-sabi/22-chung-cu-gs1-vin-smart-45m2/7.webp",
      "/asset/anhweb/wabi-sabi/22-chung-cu-gs1-vin-smart-45m2/8.webp",
      "/asset/anhweb/wabi-sabi/22-chung-cu-gs1-vin-smart-45m2/9.webp"
    ]
  },
  {
    id: "23-nha-at-ien-bien-130m2",
    index: "16",
    title: "NHÀ ĐẤT ĐIỆN BIÊN 130m²",
    tagline: "Dự án • Diện tích: 130 m²",
    description: "Thiết kế tôn vinh tính nguyên bản của vật liệu thông qua các hệ dầm gỗ thô nguyên khối để lộ vân nứt tự nhiên, kết hợp với sàn đá mài (Terrazzo) hạt lớn. Không gian áp dụng nghệ thuật sắp đặt ánh sáng Chiaroscuro (Tương phản sáng - tối), tạo ra những khoảng tối tĩnh lặng xen kẽ những vệt nắng đổ từ giếng trời. Sự hiện diện của một tiểu cảnh tĩnh (vườn khô Zen) đặt tại giếng trời đóng vai trò là lõi năng lượng, kết nối ngôi nhà trực tiếp với các yếu tố tự nhiên: Nước, Đá, Gỗ và Không khí.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách wabi-sabi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Điện Biên",
      "Diện tích: 130 m²",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Điện Biên",
    area: "130 m²",
    style: "WABISABI",
    mainImage: "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-1.webp",
    gallery: [
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-1.webp",
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-10.webp",
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-11.webp",
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-12.webp",
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-13.webp",
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-14.webp",
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-15.webp",
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-16.webp",
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-17.webp",
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-18.webp",
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-19.webp",
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-2.webp",
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-20.webp",
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-3.webp",
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-4.webp",
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-5.webp",
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-6.webp",
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-7.webp",
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-8.webp",
      "/asset/anhweb/wabi-sabi/23-nha-dat-dien-bien-130m2/kb-9.webp"
    ]
  },
  {
    id: "3-chung-cu-115-m2",
    index: "17",
    title: "CHUNG CƯ 115m²",
    tagline: "Dự án • Diện tích: 115  m²",
    description: "Chúng tôi tiến hành mềm hóa cấu trúc thô cứng của căn hộ bằng các hệ trần và hốc tường bo cong (Curved architecture). Toàn bộ bề mặt tường được phủ sơn hiệu ứng vi xi măng (Microcement) hoặc sơn đất sét với bề mặt gai nhẹ, hấp thụ ánh sáng một cách khuếch tán, triệt tiêu sự bóng bẩy. Nội thất ưu tiên các hình khối hữu cơ (Organic shapes), sofa vải thô tự nhiên (Bouclé) mang tông màu của đất và cát, tạo ra một ốc đảo tĩnh lặng tách biệt khỏi nhịp sống đô thị.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách wabi-sabi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 115  m²",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "115  m²",
    style: "WABISABI",
    mainImage: "/asset/anhweb/wabi-sabi/3-chung-cu-115-m2/1.webp",
    gallery: [
      "/asset/anhweb/wabi-sabi/3-chung-cu-115-m2/1.webp",
      "/asset/anhweb/wabi-sabi/3-chung-cu-115-m2/10.webp",
      "/asset/anhweb/wabi-sabi/3-chung-cu-115-m2/11.webp",
      "/asset/anhweb/wabi-sabi/3-chung-cu-115-m2/12.webp",
      "/asset/anhweb/wabi-sabi/3-chung-cu-115-m2/13.webp",
      "/asset/anhweb/wabi-sabi/3-chung-cu-115-m2/14.webp",
      "/asset/anhweb/wabi-sabi/3-chung-cu-115-m2/15.webp",
      "/asset/anhweb/wabi-sabi/3-chung-cu-115-m2/16.webp",
      "/asset/anhweb/wabi-sabi/3-chung-cu-115-m2/17.webp",
      "/asset/anhweb/wabi-sabi/3-chung-cu-115-m2/18.webp",
      "/asset/anhweb/wabi-sabi/3-chung-cu-115-m2/19.webp",
      "/asset/anhweb/wabi-sabi/3-chung-cu-115-m2/2.webp",
      "/asset/anhweb/wabi-sabi/3-chung-cu-115-m2/3.webp",
      "/asset/anhweb/wabi-sabi/3-chung-cu-115-m2/4.webp",
      "/asset/anhweb/wabi-sabi/3-chung-cu-115-m2/5.webp",
      "/asset/anhweb/wabi-sabi/3-chung-cu-115-m2/6.webp",
      "/asset/anhweb/wabi-sabi/3-chung-cu-115-m2/7.webp",
      "/asset/anhweb/wabi-sabi/3-chung-cu-115-m2/8.webp"
    ]
  },
  {
    id: "2-chung-c-matrixone---126m2",
    index: "02",
    title: "CHUNG CƯ MATRIXONE - 126m²",
    tagline: "Dự án • Diện tích: 126m²",
    description: "Phương án ứng dụng giải pháp bố trí không gian mở liên hoàn (Open-plan concept) giữa Khách - Bếp - Ăn nhằm nhân đôi cảm giác rộng rãi. Điểm chạm thị giác được xử lý bằng các vật liệu có tính phản chiếu cao như kính xám khói, nẹp kim loại titan và đá nung kết (Sintered Stone) vân lớn. Hệ thống ánh sáng được kịch bản hóa (Lighting scenario) với các dải LED âm trần định hình tuyến tính, biến căn hộ thành một không gian lounge sang trọng vào ban đêm.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách hiện đại.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 126m²",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "126m²",
    style: "HIEN_DAI",
    mainImage: "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/1.webp",
    gallery: [
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/1.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/10.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/11.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/12.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/13.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/14.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/15.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/16.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/17.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/18.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/19.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/2.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/20.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/21.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/22.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/23.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/24.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/25.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/26.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/27.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/28.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/29.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/3.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/30.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/31.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/32.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/33.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/34.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/35.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/36.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/37.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/38.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/39.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/4.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/40.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/41.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/42.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/43.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/44.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/45.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/46.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/47.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/48.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/49.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/5.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/50.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/6.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/7.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/8.webp",
      "/asset/anhweb/hien-dai/2-chung-cu-matrixone-126m2/anh-3d/9.webp"
    ]
  },
  {
    id: "21-chung-c-hh4c-linh-m---p-thng-2-cn",
    index: "21",
    title: "CHUNG CƯ HH4C LINH ĐÀM - ĐẬP THÔNG 2 CĂN",
    tagline: "Dự án • Diện tích: Không xác định",
    description: "Phương án ứng dụng giải pháp bố trí không gian mở liên hoàn (Open-plan concept) giữa Khách - Bếp - Ăn nhằm nhân đôi cảm giác rộng rãi. Điểm chạm thị giác được xử lý bằng các vật liệu có tính phản chiếu cao như kính xám khói, nẹp kim loại titan và đá nung kết (Sintered Stone) vân lớn. Hệ thống ánh sáng được kịch bản hóa (Lighting scenario) với các dải LED âm trần định hình tuyến tính, biến căn hộ thành một không gian lounge sang trọng vào ban đêm.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách hiện đại.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: Không xác định",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "Không xác định",
    style: "HIEN_DAI",
    mainImage: "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thi-cong/1.webp",
    gallery: [
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thi-cong/1.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thi-cong/10.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thi-cong/11.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thi-cong/12.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thi-cong/13.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thi-cong/14.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thi-cong/15.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thi-cong/2.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thi-cong/3.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thi-cong/4.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thi-cong/5.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thi-cong/6.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thi-cong/7.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thi-cong/8.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thi-cong/9.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/1-khach-bep-1.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/1-khach-bep-10.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/1-khach-bep-2.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/1-khach-bep-3.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/1-khach-bep-4.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/1-khach-bep-5.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/1-khach-bep-6.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/1-khach-bep-7.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/1-khach-bep-8.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/1-khach-bep-9.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/2-master-1.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/2-master-2.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/2-master-3.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/2-master-4.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/2-master-5.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/2-master-6.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/3-p-ngu-con-1-1.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/3-p-ngu-con-1-2.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/3-p-ngu-con-1-3.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/3-p-ngu-con-1-4.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/4-p-ngu-con-2-1.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/4-p-ngu-con-2-2.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/4-p-ngu-con-2-3.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/4-p-ngu-con-2-4.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/5-ban-cong-1.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/5-ban-cong-2.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/6-ve-sinh-chung-1.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/6-ve-sinh-chung-2.webp",
      "/asset/anhweb/hien-dai/21-chung-cu-hh4c-linh-dam-dap-thong-2-can/thiet-ke/6-ve-sinh-chung-3.webp"
    ]
  },
  {
    id: "1-nh-ci-to-2-tng---thi-nguyn",
    index: "01",
    title: "NHÀ CẢI TẠO 2 TẦNG - THÁI NGUYÊN",
    tagline: "Dự án • Diện tích: Không xác định",
    description: "Không gian được phát triển theo trục dọc với sự chuyển tiếp mượt mà từ khoảng đệm (Genkan) vào phòng khách. Chúng tôi ứng dụng các hệ vách nan gỗ (Slatted wood panels) đóng vai trò làm vách ngăn hờ, cho phép ánh sáng tự nhiên từ giếng trời luân chuyển xuyên suốt các tầng mà không làm mất đi tính riêng tư. Sàn gỗ tự nhiên bản lớn kết hợp với các mảng tường sơn hiệu ứng matte tông màu beige tạo nên chiều sâu cảm xúc vững chãi cho một ngôi nhà gắn kết thế hệ.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách japandi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: Không xác định",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "Không xác định",
    style: "JAPANDI",
    mainImage: "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/1.webp",
    gallery: [
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/1.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/11.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/13.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/15.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/17.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/19.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/20.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/23.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/25.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/27.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/29.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/3.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/31.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/33.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/35.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/37.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/39.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/41.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/43.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/44-1.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/44-2.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/44-3.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/44-4.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/45-1.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/45-2.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/46-1.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/46-2.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/46-3.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/46-4.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/46-5.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/47.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/5.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/7.webp",
      "/asset/anhweb/japandi/1-nha-cai-tao-2-tang-thai-nguyen/3d/9.webp"
    ]
  },
  {
    id: "16-nh-ph---ni-tht---ng-vn-chng--4x15",
    index: "16",
    title: "NHÀ PHỐ - NỘI THẤT - NGÕ VĂN CHƯƠNG -4X15",
    tagline: "Dự án • Diện tích: 4x15",
    description: "Không gian được phát triển theo trục dọc với sự chuyển tiếp mượt mà từ khoảng đệm (Genkan) vào phòng khách. Chúng tôi ứng dụng các hệ vách nan gỗ (Slatted wood panels) đóng vai trò làm vách ngăn hờ, cho phép ánh sáng tự nhiên từ giếng trời luân chuyển xuyên suốt các tầng mà không làm mất đi tính riêng tư. Sàn gỗ tự nhiên bản lớn kết hợp với các mảng tường sơn hiệu ứng matte tông màu beige tạo nên chiều sâu cảm xúc vững chãi cho một ngôi nhà gắn kết thế hệ.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách japandi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: 4x15",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "4x15",
    style: "JAPANDI",
    mainImage: "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-1/43.webp",
    gallery: [
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-1/43.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-4/1.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-4/10.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-4/12.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-4/3.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-4/5.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-4/7.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-4/9.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-6/23.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-6/25.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-6/35.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-6/37.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-6/39.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-6/41.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-7/1.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-7/11.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-7/13.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-7/15.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-7/17.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-7/19.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-7/21.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-7/3.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-7/5.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-7/55.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-7/57.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-7/61.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-7/7.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-7/9.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-tum/27.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-tum/29.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-tum/31.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-tum/33.webp",
      "/asset/anhweb/japandi/16-nha-pho-noi-that-ngo-van-chuong-4x15/tang-tum/59.webp"
    ]
  },
  {
    id: "18-chung-c-ct3c-nam-cng",
    index: "18",
    title: "CHUNG CƯ CT3C NAM CƯỜNG",
    tagline: "Dự án • Diện tích: Không xác định",
    description: "Chúng tôi tiến hành mềm hóa cấu trúc thô cứng của căn hộ bằng các hệ trần và hốc tường bo cong (Curved architecture). Toàn bộ bề mặt tường được phủ sơn hiệu ứng vi xi măng (Microcement) hoặc sơn đất sét với bề mặt gai nhẹ, hấp thụ ánh sáng một cách khuếch tán, triệt tiêu sự bóng bẩy. Nội thất ưu tiên các hình khối hữu cơ (Organic shapes), sofa vải thô tự nhiên (Bouclé) mang tông màu của đất và cát, tạo ra một ốc đảo tĩnh lặng tách biệt khỏi nhịp sống đô thị.",
    bullets: [
      "Không gian được tối ưu hóa để phù hợp với nhu cầu sinh hoạt của gia chủ.",
      "Sử dụng tông màu và vật liệu đặc trưng của phong cách wabi-sabi.",
      "Mỗi chi tiết nội thất đều được lựa chọn kỹ lưỡng để tạo nên tổng thể hài hòa."
    ],
    highlightsHeader: "THÔNG TIN DỰ ÁN:",
    highlights: [
      "Loại hình: Dự án",
      "Địa điểm: Hà Nội",
      "Diện tích: Không xác định",
      "Thiết kế & thi công: NOU.Design"
    ],
    location: "Hà Nội",
    area: "Không xác định",
    style: "WABISABI",
    mainImage: "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-1/1.webp",
    gallery: [
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-1/1.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-1/10.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-1/11.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-1/2.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-1/3.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-1/4.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-1/5.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-1/6.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-1/7.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-1/7a.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-1/8.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-1/9.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-2/1.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-2/11.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-2/13.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-2/15.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-2/17.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-2/19.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-2/27.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-2/29.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-2/3.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-2/31.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-2/33.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-2/35.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-2/37.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-2/39.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-2/41.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-2/43.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-2/5.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-2/7.webp",
      "/asset/anhweb/wabi-sabi/18-chung-cu-ct3c-nam-cuong/phuong-an-2/9.webp"
    ]
  },
];
